'use client';

import React from 'react';
import { MessageSquare, Calendar, Zap } from 'lucide-react';

export default function UserAIHistory() {
  const history = [
    {
      query: 'Recommend a good mechanical keyboard for coding under $100.',
      intent: 'RECOMMENDATION',
      response: 'Based on our catalog, I recommend the **Minimalist Wireless Keyboard** ($89.99). It is fully compatible with Next.js workflows, offers Bluetooth multi-device sync, has linear tactile switches ideal for coding, and holds a strong average rating of 4.8★.',
      date: 'June 21, 2026',
    },
    {
      query: 'Is the smart bottle better than the backpack?',
      intent: 'COMPARISON',
      response: 'These items serve different needs:\n- The **Smart Stainless Steel Bottle** ($39.00) tracks daily hydration with electronic counters.\n- The **Leather Everyday Backpack** ($129.50) handles daily commutes and stores electronics.\n\nChoose the bottle if you need active fitness tracking, or the backpack for travel and storage.',
      date: 'June 20, 2026',
    },
    {
      query: 'What specs do the headphones have?',
      intent: 'ADVISOR',
      response: 'The **Noise Cancelling Headphones** ($249.99) offer active hybrid noise reduction (ANC), 40-hour battery capacity, Hi-Res audio output, and plush memory foam padding. Rating: 4.9★ with active stock.',
      date: 'June 19, 2026',
    },
  ];

  const getIntentColor = (intent: string) => {
    switch (intent) {
      case 'RECOMMENDATION': return 'bg-[#4F46E5]/10 text-[#4F46E5] border-[#4F46E5]/20';
      case 'COMPARISON': return 'bg-[#06B6D4]/10 text-[#06B6D4] border-[#06B6D4]/20';
      default: return 'bg-[#F59E0B]/10 text-[#F59E0B] border-[#F59E0B]/20';
    }
  };

  return (
    <div className="space-y-6">
      <div className="space-y-1">
        <h2 className="text-2xl font-bold tracking-tight">AI Conversation Logs</h2>
        <p className="text-zinc-500 dark:text-zinc-400 text-sm">
          Review your previous questions and the responses generated by E-Shop&apos;s agentic AI layers.
        </p>
      </div>

      <div className="space-y-6">
        {history.map((item, idx) => (
          <div 
            key={idx} 
            className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-xs dark:border-zinc-800 dark:bg-zinc-900 transition-colors"
          >
            {/* Header info */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-4 border-b border-zinc-100 dark:border-zinc-800">
              <div className="flex items-center gap-2">
                <MessageSquare className="h-4 w-4 text-zinc-400" />
                <span className="text-xs font-semibold text-zinc-500 dark:text-zinc-400">Query log #{3 - idx}</span>
              </div>
              <div className="flex items-center gap-3">
                <span className={`px-2 py-0.5 rounded-md text-[10px] font-bold border ${getIntentColor(item.intent)}`}>
                  {item.intent}
                </span>
                <span className="flex items-center gap-1 text-[11px] text-zinc-400 font-semibold">
                  <Calendar className="h-3 w-3" />
                  {item.date}
                </span>
              </div>
            </div>

            {/* Prompt vs Response */}
            <div className="mt-4 space-y-4">
              <div>
                <p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400 dark:text-zinc-500">Your Query</p>
                <p className="mt-1 text-sm font-bold text-zinc-900 dark:text-zinc-100">&ldquo;{item.query}&rdquo;</p>
              </div>

              <div className="rounded-xl bg-zinc-50 p-4 dark:bg-zinc-800/40 border border-zinc-100 dark:border-zinc-800/50">
                <p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400 dark:text-zinc-500 mb-2 flex items-center gap-1">
                  <Zap className="h-3 w-3 text-[#06B6D4]" />
                  <span>Agent Answer</span>
                </p>
                <p className="text-sm text-zinc-700 dark:text-zinc-300 whitespace-pre-line leading-relaxed">
                  {item.response}
                </p>
              </div>
            </div>

          </div>
        ))}
      </div>
    </div>
  );
}
